// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.team2667.robotcannon;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftMotor;
    public static SpeedController driveTrainRightMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static Compressor pneumaticsCompressor;
    public static Solenoid pneumaticsSolenoid_A;
    public static Solenoid pneumaticsSolenoid_B;
    public static Solenoid pneumaticsSolenoid_X;
    public static Solenoid pneumaticsSolenoid_Y;
    public static Gyro sensorsGyro;
    public static AnalogInput sensorsUltraSonicSensor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "LeftMotor", (Talon) driveTrainLeftMotor);
        
        driveTrainRightMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "RightMotor", (Talon) driveTrainRightMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
        
        driveTrainRobotDrive.setSafetyEnabled(false);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.25);
        driveTrainRobotDrive.setMaxOutput(0.5);
        

        pneumaticsCompressor = new Compressor(0);
        
        
        pneumaticsSolenoid_A = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "Solenoid_A", pneumaticsSolenoid_A);
        
        pneumaticsSolenoid_B = new Solenoid(0, 1);
        LiveWindow.addActuator("Pneumatics", "Solenoid_B", pneumaticsSolenoid_B);
        
        pneumaticsSolenoid_X = new Solenoid(0, 2);
        LiveWindow.addActuator("Pneumatics", "Solenoid_X", pneumaticsSolenoid_X);
        
        pneumaticsSolenoid_Y = new Solenoid(0, 3);
        LiveWindow.addActuator("Pneumatics", "Solenoid_Y", pneumaticsSolenoid_Y);
        
        sensorsGyro = new Gyro(0);
        LiveWindow.addSensor("Sensors", "Gyro", sensorsGyro);
        sensorsGyro.setSensitivity(0.007);
        sensorsUltraSonicSensor = new AnalogInput(1);
        LiveWindow.addSensor("Sensors", "UltraSonicSensor", sensorsUltraSonicSensor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
